Statement/Controllers/StatementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessTrip.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Statement.Services;
using Statement.Data;
using Statement.ViewModel;
using Microsoft.EntityFrameworkCore;
using Statement.Filters.AuthFilter;
using Statement.Models;

namespace Statement.Controllers
{
    [Auth]
    public class StatementController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IStatementService _statementService;
        private ApplicationDbContext _context;

        public StatementController(IStatementService statementService, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _statementService = statementService;
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var userName = HttpContext.User.Claims.FirstOrDefault(user => user.Type.EndsWith("name"))?.Value;

            if (userName == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByNameAsync(userName);

            if (user == null)
            {
                return NotFound();
            }

            var allStatements = _context.AspUserStatement.Where(x => x.Id == user.Id).Join(_context.AspStatement,
                                                     userStatement => userStatement.StatementId,
                                                     statement => statement.StatementId,
                                                     (userStatement, statement) => statement).ToList();


            var statementViewModel = new StatementViewModel()
            {
                Statements = allStatements
            };

            var statements = _statementService.GetAllStatements();

            return View(statementViewModel);
        }


        //[HttpGet]
        //public FileResult PDFDownload()
        //{

        //    var statements = _statementService.GetAllStatements().Statements.FirstOrDefault();

        //    byte[] pdfByte = _statementService.WorkWithDocFile(statements);

        //    return File(pdfByte, "i.docx", "doc");
        //}

        //[HttpGet]
        //public FileStreamResult PDFDownload()
        //{
        //    var statements = _statementService.GetAllStatements().Statements.FirstOrDefault();
        //    byte[] pdfByte = _statementService.WorkWithDocFile(statements);
        //    var memoryStream = new MemoryStream(pdfByte);

        //    return File(memoryStream, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Заява на відрядження.doc");
        //}

        //admin download
        [HttpGet]
        public FileStreamResult PDFDownload(int id)
        {
            var statements = _statementService.GetAllStatements().Statements.FirstOrDefault(statement => statement.StatementId == id);
            byte[] pdfByte = _statementService.WorkWithDocFile(statements);
            var memoryStream = new MemoryStream(pdfByte);
            return File(memoryStream, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Заява на відрядження.doc");
        }



        [HttpGet]
        public IActionResult CreateStatement()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateStatement(CreateStatementViewModel statement)
        {
            if (ModelState.IsValid)
            {
                var userName = HttpContext.User.Claims.FirstOrDefault(user => user.Type.EndsWith("name"))?.Value;

                if (userName != null)
                {
                    var user = await _userManager.FindByNameAsync(userName);
                    var applicationStatement = (ApplicationStatement)statement;
                    await _statementService.CreateStatement(applicationStatement, user);

                    if (HttpContext.User.Identity.Name == "Admin")
                    {

                        return RedirectToAction(nameof(Statements));
                    }
                    else
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }

            return View(statement);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ApplicationStatement statement)
        {
            if (ModelState.IsValid)
            {
                var userName = HttpContext.User.Claims.FirstOrDefault(user => user.Type.EndsWith("name"))?.Value;

                if (userName != null)
                {
                    var user = await _userManager.FindByNameAsync(userName);
                    await _statementService.CreateStatement(statement, user);
                    //_statementService.WorkWithDocFile(statement);

                    return RedirectToAction(nameof(Index));
                }
            }

            return View(statement);
        }

        //admin list of statements
        public IActionResult Statements()
        {
            var allStatements = _context.AspStatement.Join(_context.AspCurrentStatus,
                                                        statement => statement.StatementId,
                                                        currentStatus => currentStatus.StatementId,
                                                        (statement, currentStatus) => new StatementWithAllStatuses
                                                        {
                                                            Statement = statement,
                                                            CurrentStatus = currentStatus
                                                        }).ToList();
            var statuses = _context.AspStatus.ToList();
            foreach (var statement in allStatements)
            {
                statement.CurrentStatus.Status = statuses.
                    FirstOrDefault(status => status.StatusId == statement.CurrentStatus.StatusId);
            }
            return View(allStatements);
        }

        ////user list of statements
        //public async Task<IActionResult> Statements()
        //{
        //    var userName = HttpContext.User.Claims.FirstOrDefault(user => user.Type.EndsWith("name"))?.Value;
        //    if (userName == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var user = await _userManager.FindByNameAsync(userName);
        //    if (user == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var allStatements = userStatements.Join(_context.AspStatement,
        //                                             userStatement => userStatement.StatementId,
        //                                             statement => statement.StatementId,
        //                                             (userStatement, statement) => statement).ToList();
        //    return View(allStatements);
        //}

        //admin delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //
            var statement = await _context.AspStatement.FindAsync(id);
            if (statement == null)
            {
                return NotFound();
            }
            //deleting on cascade
            _context.AspStatement.Remove(statement);
            _context.SaveChanges();
            return Redirect("/Statement/Statements");
        }

        ////user delete
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var statement = await _context.AspStatement.FindAsync(id);
        //    if (statement == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var userName = HttpContext.User.Claims.FirstOrDefault(user => user.Type.EndsWith("name"))?.Value;
        //    if (userName == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var user = await _userManager.FindByNameAsync(userName);
        //    if(user == null)
        //    {
        //        return NotFound();
        //    }
        //    //
        //    var userStatement = await _context.AspUserStatement.FindAsync(user.Id, statement.StatementId);
        //    if (userStatement == null)
        //    {
        //        return NotFound();
        //    }            
        //    //deleting on cascade
        //    _context.AspStatement.Remove(statement);
        //    _context.SaveChanges();
        //    return Redirect("/Statement/Statements");
        //}

        //admin edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var statement = await _context.AspStatement.FindAsync(id);
            if (statement == null)
            {
                return NotFound();
            }

            var statuses = _context.AspStatus.ToList();
            var statementCurrentStatus = _context.AspCurrentStatus.
                FirstOrDefault(currentStatus => currentStatus.StatementId == statement.StatementId);
            statementCurrentStatus.Status = statuses.
                FirstOrDefault(status => status.StatusId == statementCurrentStatus.StatusId);

            var statementHistoryOfStatuses = _context.AspHistoryOfStatus.

Statement/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

Statement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Відрядження</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Відрядження</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        @if (ViewContext.HttpContext.User.Identity.Name == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statement" asp-action="Statements">Заяви</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statement" asp-action="Index">Заяви</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Проєкт по відрядженнях
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>